local CarsData = {
	StarterCars = {
		{
			Id = "car_sport",
			Name = "Crimson Falcon",
			MaxSpeed = 100,
			Acceleration = 5,
			ModelName = "CrimsonFalconModel",
			Description = "Sleek and fast, perfect for beginners eager to burn the streets.",
			Rarity = "Common",
		},
		{
			Id = "car_muscle",
			Name = "Thunderclap",
			MaxSpeed = 90,
			Acceleration = 10,
			ModelName = "ThunderclapModel",
			Description = "Powerful muscle car with a roaring engine and quick acceleration.",
			Rarity = "Common",
		},
		{
			Id = "car_compact",
			Name = "Shadow Sprint",
			MaxSpeed = 110,
			Acceleration = 2,
			ModelName = "ShadowSprintModel",
			Description = "Small and nimble, ideal for weaving through tight city corners.",
			Rarity = "Common",
		},
	},

	BountyCars = {
		{
			Id = "car_nightblade",
			Name = "Nightblade",
			MaxSpeed = 140,
			Acceleration = 10,
			ModelName = "NightbladeModel",
			Description = "A stealthy, ultra-fast car with superior handling and night vision HUD.",
			Requirements = {
				Level = 15,
				Rebirth = 0,
				Achievements = { "Win 20 races" },
			},
			SpecialPerks = { "Improved drifting", "Reduced tire wear" },
			Rarity = "Uncommon",
		},
		{
			Id = "car_ironphantom",
			Name = "Iron Phantom",
			MaxSpeed = 160,
			Acceleration = 5,
			ModelName = "IronPhantomModel",
			Description = "A heavily armored racer built for those who dare to dominate.",
			Requirements = {
				Level = 20,
				Rebirth = 1,
				Achievements = { "Collect 100 bounties" },
			},
			SpecialPerks = { "Damage resistance", "Bonus bounty rewards" },
			Rarity = "Rare",
		},
		{
			Id = "car_stormrunner",
			Name = "Stormrunner",
			MaxSpeed = 180,
			Acceleration = 20,
			ModelName = "StormrunnerModel",
			Description = "Lightning-fast with explosive acceleration, the Stormrunner leaves opponents in the dust.",
			Requirements = {
				Level = 25,
				Rebirth = 2,
				Achievements = { "Complete all side quests" },
			},
			SpecialPerks = { "Boost cooldown reduced", "XP gain increased by 10%" },
			Rarity = "Epic",
		},
		{
			Id = "car_glacier",
			Name = "Glacier",
			MaxSpeed = 100,
			Acceleration = 5,
			ModelName = "GlacierModel",
			Description = "A cool, calm vehicle with enhanced traction for slippery conditions.",
			Requirements = {
				Level = 10,
				Rebirth = 0,
				Achievements = { "Win 5 bounties" },
			},
			SpecialPerks = { "Improved handling on wet roads" },
			Rarity = "Uncommon",
		},
	},

	RebirthCars = {
		{
			Id = "car_phoenix",
			Name = "Phoenix",
			MaxSpeed = 150,
			Acceleration = 5,
			ModelName = "PhoenixModel",
			BadgeId = 23456793,
			Description = "Reborn from the ashes, this car boasts fiery speed and resilience.",
			Requirements = {
				Level = 30,
				Rebirth = 5,
				Achievements = { "Rebirth 5 times" },
			},
			SpecialPerks = { "Afterburner boost", "Rebirth bonus XP" },
			Rarity = "Rare",
		},
		{
			Id = "car_dragonfire",
			Name = "Dragon Fire",
			MaxSpeed = 170,
			Acceleration = 10,
			ModelName = "DragonFireModel",
			BadgeId = 23456794,
			Description = "Unleash the fury of the dragon with blazing speed and fiery aesthetics.",
			Requirements = {
				Level = 35,
				Rebirth = 10,
				Achievements = { "Rebirth 10 times" },
			},
			SpecialPerks = { "Fire trail effect", "Increased damage resistance" },
			Rarity = "Epic",
		},
		{
			Id = "car_titanshade",
			Name = "Titan Shade",
			MaxSpeed = 190,
			Acceleration = 15,
			ModelName = "TitanShadeModel",
			BadgeId = 23456795,
			Description = "A colossal machine with unmatched power and speed, fit for a titan.",
			Requirements = {
				Level = 40,
				Rebirth = 15,
				Achievements = { "Rebirth 15 times" },
			},
			SpecialPerks = { "Increased top speed" },
			Rarity = "Epic",
		},
		{
			Id = "car_leviathan",
			Name = "Leviathan",
			MaxSpeed = 200,
			Acceleration = 20,
			ModelName = "LeviathanModel",
			BadgeId = 23456796,
			Description = "The ultimate racing beast, dominating all with its colossal speed and power.",
			Requirements = {
				Level = 45,
				Rebirth = 20,
				Achievements = { "Rebirth 20 times" },
			},
			SpecialPerks = { "Massive boost power", "XP gain increased by 20%" },
			Rarity = "Legendary",
		},
		{
			Id = "car_zephyr",
			Name = "Zephyr",
			MaxSpeed = 210,
			Acceleration = 25,
			ModelName = "ZephyrModel",
			BadgeId = 23456797,
			Description = "As swift as the wind, the Zephyr is built for those who crave speed above all.",
			Requirements = {
				Level = 50,
				Rebirth = 25,
				Achievements = { "Rebirth 25 times" },
			},
			SpecialPerks = { "Wind trail effect", "Reduced boost cooldown" },
			Rarity = "Legendary",
		},
		{
			Id = "car_apexpredator",
			Name = "Apex Predator",
			MaxSpeed = 220,
			Acceleration = 30,
			ModelName = "ApexPredatorModel",
			BadgeId = 23456798,
			Description = "The pinnacle of racing technology, designed for those who dominate the competition.",
			Requirements = {
				Level = 55,
				Rebirth = 30,
				Achievements = { "Rebirth 30 times" },
			},
			SpecialPerks = { "Ultimate boost", "Increased damage resistance" },
			Rarity = "Legendary",
		},
		{
			Id = "car_everfrost",
			Name = "Everfrost",
			MaxSpeed = 230,
			Acceleration = 35,
			ModelName = "EverfrostModel",
			BadgeId = 23456799,
			Description = "A chillingly fast car with ice-cold precision and control.",
			Requirements = {
				Level = 60,
				Rebirth = 35,
				Achievements = { "Rebirth 35 times" },
			},
			SpecialPerks = { "Ice trail effect", "Improved handling" },
			Rarity = "Legendary",
		},
		{
			Id = "car_solarflare",
			Name = "Solar Flare",
			MaxSpeed = 240,
			Acceleration = 40,
			ModelName = "SolarFlareModel",
			BadgeId = 23456800,
			Description = "Harness the power of the sun with blazing speed and radiant design.",
			Requirements = {
				Level = 65,
				Rebirth = 40,
				Achievements = { "Rebirth 40 times" },
			},
			SpecialPerks = { "Solar trail effect", "Increased top speed" },
			Rarity = "Mythic",
		},
		{
			Id = "car_cosmicstorm",
			Name = "Cosmic Storm",
			MaxSpeed = 250,
			Acceleration = 45,
			ModelName = "CosmicStormModel",
			BadgeId = 23456801,
			Description = "A cosmic marvel that combines speed, power, and otherworldly aesthetics.",
			Requirements = {
				Level = 70,
				Rebirth = 45,
				Achievements = { "Rebirth 45 times" },
			},
			SpecialPerks = { "Cosmic trail effect", "Ultimate boost" },
			Rarity = "Legendary",
		},
		{
			Id = "car_infernoblaze",
			Name = "Inferno Blaze",
			MaxSpeed = 300,
			Acceleration = 50,
			ModelName = "InfernoBlazeModel",
			BadgeId = 23456802,
			Description = "A fiery beast that scorches the competition with its blazing speed and power.",
			Requirements = {
				Level = 75,
				Rebirth = 50,
				Achievements = { "Rebirth 50 times" },
			},
			SpecialPerks = { "Inferno trail effect", "Increased damage resistance" },
			Rarity = "Godly",
		},
	},

	GamePassCars = {
		{
			Id = "car_neonvortex",
			Name = "Neon Vortex",
			MaxSpeed = 200,
			Acceleration = 20,
			ModelName = "NeonVortexModel",
			GamePassId = 12345678,
			Description = "An eye-catching futuristic racer with neon lights and unmatched speed.",
			SpecialPerks = { "Customizable neon glow", "Exclusive sound effects" },
			Tradeable = true,
			Rarity = "Exclusive",
		},
		{
			Id = "car_royalphantom",
			Name = "Royal Phantom",
			MaxSpeed = 220,
			Acceleration = 20,
			ModelName = "RoyalPhantomModel",
			BadgeId = 34567891,
			GamePassId = 87654321,
			Description = "Luxurious and powerful, only for the elite racers.",
			SpecialPerks = { "Exclusive horn", "Armor plating" },
			Tradeable = true,
			Rarity = "Mythic",
		},
		{
			Id = "car_crimsonhawk",
			Name = "Crimson Hawk",
			MaxSpeed = 300,
			Acceleration = 30,
			ModelName = "CrimsonHawkModel",
			GamePassId = 11223344,
			Description = "Sleek design with aggressive styling and blazing speed.",
			SpecialPerks = { "Boost trail effect", "VIP-only decals" },
			Tradeable = true,
			Rarity = "Godly",
		},
	},
}

return CarsData
